name: Stolon Build and Test

on:
  push:
    branches:
      - 'master'
      - 'ci'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.int_matrix.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Build integration tests binary
        run: go test -c ./tests/integration/ -o bin/integration-tests

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./bin

      - name: Generate integration tests matrix
        id: int_matrix
        shell: bash
        run: |
          tests=$(./bin/integration-tests -test.list '.*' | jq -R . | jq -sc .)
          echo "tests=${tests}" | tee -a "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      max-parallel: 16
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.build.outputs.tests) }}
    steps:
      - name: Install dependencies
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y postgresql-common consul
          echo create_main_cluster=off | sudo tee -a /etc/postgresql-common/createcluster.conf
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install -y postgresql

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./bin

      - name: Run integration tests
        env:
          STOLON_TEST_STORE_BACKEND: consul
          POSTGRES_PATH: /usr/lib/postgresql/16
          TMPDIR: /tmp/stolontemp
          STKEEPER_BIN: ${{ github.workspace }}/bin/stolon-keeper
          STSENTINEL_BIN: ${{ github.workspace }}/bin/stolon-sentinel
          STPROXY_BIN: ${{ github.workspace }}/bin/stolon-proxy
          STCTL_BIN: ${{ github.workspace }}/bin/stolonctl
          CONSUL_BIN: /usr/bin/consul
          INTEGRATION: 1
        run: |
          mkdir -p $TMPDIR
          chmod +x ./bin/*
          export PATH=$POSTGRES_PATH/bin:$PATH
          ./bin/integration-tests -test.parallel 1 -test.v -test.run ^${{ matrix.test }}$
